#!/bin/bash

set -e

OUT=$(./2.1.test 2>&1 | sed 's/ @.*/ @.../')
EXPECTED="Default-Constructing @...
Copy-Constructing @...
Destructing @...
Destructing @...
Copy-Constructing @...
Default-Constructing @...
Default-Constructing @...
Destructing @...
Destructing @...
Destructing @..."

if [[ "$OUT" = "$EXPECTED" ]]; then
  echo "SUCCESS"
else
  echo "FAILED: Expected: '$EXPECTED', and instead, got '$OUT'"
  exit 1
fi
